Repository gammaStrahlung/monopoly_server, pull requests merged in 2024-05, with the labels that each got.

#40 Fix initializeGameBoard
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
Labels: bug

#43 Websocket improvements
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayer.java
  src/main/java/at/gammastrahlung/monopoly_server/network/dtos/ServerMessage.java
  src/main/java/at/gammastrahlung/monopoly_server/network/websocket/MonopolyMessageHandler.java
Labels: enhancement

#42 Dice Rolling
  src/main/java/at/gammastrahlung/monopoly_server/game/Dice.java
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/network/dtos/ServerMessage.java
  src/main/java/at/gammastrahlung/monopoly_server/network/websocket/MonopolyMessageHandler.java
  src/test/java/at/gammastrahlung/monopoly_server/game/DiceTests.java
Labels: enhancement

#52 Change docker base image to eclipse-temurin
  Dockerfile
Labels: bug

#50 Feature/go to jail
  src/main/java/at/gammastrahlung/monopoly_server/game/FieldActionHandler.java
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/game/Player.java
  src/test/java/at/gammastrahlung/monopoly_server/game/FieldActionHandlerTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/PlayerTest.java
Labels: enhancement

#49 Update README
  README.md
Labels: documentation

#53 Free parking
  src/main/java/at/gammastrahlung/monopoly_server/game/FieldActionHandler.java
  src/test/java/at/gammastrahlung/monopoly_server/game/FieldActionHandlerTests.java
Labels: enhancement

#58 Move Avatar extensions on Server
  src/main/java/at/gammastrahlung/monopoly_server/game/Player.java
  src/main/java/at/gammastrahlung/monopoly_server/network/websocket/MonopolyMessageHandler.java
Labels: enhancement

#60 Homepage with version
  .github/workflows/docker.yml
  build.gradle
  src/main/java/at/gammastrahlung/monopoly_server/network/Homepage.java
Labels: enhancement

#44 Implement payment logic in PaymentSystem class
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/game/Player.java
  src/main/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayer.java
  src/main/java/at/gammastrahlung/monopoly_server/game/gameboard/Railroad.java
  src/main/java/at/gammastrahlung/monopoly_server/network/dtos/ClientMessage.java
  src/main/java/at/gammastrahlung/monopoly_server/network/websocket/MonopolyMessageHandler.java
  src/test/java/at/gammastrahlung/monopoly_server/game/GameTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayerTest.java
Labels: enhancement

#66 Refactor rent payment
  src/main/java/at/gammastrahlung/monopoly_server/game/FieldActionHandler.java
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayer.java
  src/main/java/at/gammastrahlung/monopoly_server/game/gameboard/Property.java
  src/main/java/at/gammastrahlung/monopoly_server/network/dtos/ClientMessage.java
  src/main/java/at/gammastrahlung/monopoly_server/network/websocket/MonopolyMessageHandler.java
  src/test/java/at/gammastrahlung/monopoly_server/game/GameTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayerTest.java
Labels: enhancement

#67 Fix SonarCloud issues
  .github/workflows/docker.yml
  .gitignore
  src/main/java/at/gammastrahlung/monopoly_server/game/Game.java
  src/main/java/at/gammastrahlung/monopoly_server/game/WebSocketPlayer.java
  src/main/java/at/gammastrahlung/monopoly_server/game/gameboard/EventCard.java
  src/main/java/at/gammastrahlung/monopoly_server/game/gameboard/GameBoard.java
  src/main/java/at/gammastrahlung/monopoly_server/game/gameboard/Property.java
  src/test/java/at/gammastrahlung/monopoly_server/game/DiceTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/EventCardTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/FieldActionHandlerTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/GameBoardTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/GameTests.java
  src/test/java/at/gammastrahlung/monopoly_server/game/PropertyTest.java
Labels: enhancement
